export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_PERMISSION = 'FETCH_PERMISSION';
export const FETCH_LIST = 'FETCH_LIST';
export const CHANGE_ACTIVE_ITEM = 'CHANGE_ACTIVE_ITEM';
export const GET_COLOR = 'GET_COLOR';
